

services:
  weather-client:
    build:
      context: .
      dockerfile: Dockerfile.weather

  subscriber:
    build:
      context: .
      dockerfile: Dockerfile.subscriber
    volumes:
      - weather-data:/app
    healthcheck:
      test: ["CMD", "sqlite3", "/app/weather.db 'SELECT count(*) FROM weather;'"]
      interval: 5s
      timeout: 3s
      retries: 5

  web-dashboard:
    build:
      context: .
      dockerfile: Dockerfile.flask
    ports:
      - "5050:5000"
    volumes:
      - weather-data:/app
    depends_on:
      subscriber:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  weather-data:
